modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="endmod"
version="1.0.0"
displayName="Endmod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="lukas, MCreator"

[[dependencies.endmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




